### ISSUE TITLE
LXImage does not consider PCManFM-Qt's Sorting set by "View" -> "Sorting" -> "Sort by"

### ISSUE THREAD

**Issue by EarthlingX** [lxqt/lximage-qt#186]
Assumed I have different picture file types in one folder (for example *.JPEG mixed with *.PNG) and the pairs have same names only with different file extensions:

-- Directory
----> picture1.jpg
----> picture1.png
----> picture2.jpg
----> picture2.png
----> picture3.jpg
----> picture3.png

When sorting these pictures in PCManFM-Qt with "View" -> "Sorting" -> "By File Type" and afterwards opening the pictures in LXImage, the presenter window does not consider the previously selected sorting variant. This behavior can be seen if one opens a random *.JPEG-picture and moves on to the next picture by clicking the right arrow: The same picture will appear again (this time with its corresponding file pendant *.PNG).

##### Expected Behavior

Presenter should display the pictures in selected order set by PCManFM-Qt's "Sorting" setting. So if I click on a *.JPEG file and have selected "Sorting by file type", I would expect that the next *.JPEG file will appear (but not *.PNG).

##### Current Behavior

Image viewer does NOT consider the selected "Sorting" variant. Currently the presenter is always showing pictures sorted by name, independent of the configured setting in "View" -> "Sorting".

##### Possible Solution

Maybe just some configuration?

##### Context

This bug appears everytime I want to watch pictures with desired sorting variant.

##### System Information

* Distribution & Version: Debian 9 (Stretch)
* Kernel: 4.9.0-8-amd64
* Qt Version: 5 (?)
* libfm-qt Version: not installed
* libqtxdg Version: not installed
* lxqt-build-tools Version: not installed
* Package version: 0.5.1-1

Thank you very much for your efforts! :-)

**Comment by tsujan** [comment]
It shouldn't because it's a separate app. Use `View` → `Show Thumbnails` and change the order by right clicking.
