### ISSUE TITLE
Image deletion and jumping forward are not consistent

### ISSUE THREAD

**Issue by EarthlingX** [lxqt/lximage-qt#187]
When deleting a currently opened picture the image viewer does not automatically jump forward to the next image. It still hangs at the "deleted" picture which has already been moved to trash bin. Therefore I have to press the "right arrow"-button on the keyboard to move to the next picture.

##### Expected Behavior

After deleting a picture, image viewer should move to the next picture automatically and display this one (instead of the deleted one).

##### Current Behavior

Image viewer does NOT jump forward to the next picture.

##### Possible Solution

Maybe just some configuration?

##### Context

This bug appears everytime when deleting pictures. For example, coming back home from holidays: Loading your pictures from the camera onto the computer and checking, which pictures are nice and which are not. In these cases I always delete the pictures when having them opened in fullscreen mode, so I can see wether they are sharp or not. When deleting a picture which is currently opened, the viewer still hangs at this picture (although it is already moved to trash bin) and I have to move onward by myself.

##### System Information

* Distribution & Version: Debian 9 (Stretch)
* Kernel: 4.9.0-8-amd64
* Qt Version: 5 (?)
* libfm-qt Version: not installed
* libqtxdg Version: not installed
* lxqt-build-tools Version: not installed
* Package version: 0.5.1-1

Thank you very much for your efforts! :-)

**Comment by tsujan** [comment]
It shouldn't because the user might want to save the file (to another place, for example).

However, that can be added as an option that's disabled by default.

**Comment by tsujan** [comment]
That's a minute detail. The main thing is about adding such an option.

**Comment by tsujan** [comment]
> If one hit delete normally one don't want to work with the "deleted" thing afterwards.

I do ;) with FeatherPad.

**Comment by tsujan** [comment]
Oh, change of mind: Maybe PCMan made it so intentionally because when the thumbnail view is shown, the next/previous image *is* shown on deleting.

This discrepancy is an issue in itself. So, I mark this as a bug. An option should be added (OK, enabled by default) and it should work consistently.

**Comment by agaida** [comment]
Please don't say that you are the prototype of a typical user :D

**Comment by tsujan** [comment]
> Please don't say that you are the prototype of a typical user

Let me confess to my sin: This is the only LXQt app I don't use, although it's a very nice app and I have it for testing and developing. Its settings didn't fit my needs (https://github.com/lxqt/lximage-qt/issues/190 was only one of them) and I didn't want to change PCMan's design; so I wrote an libfm-qt independent Qt app for personal use (not uploaded) and use it instead.

At some point, I might propose my preferred design because lximage-qt is superior to my app in several regards; I just haven't had enough time so far.

**Comment by agaida** [comment]
i suggest this move after our release :P

**Comment by tsujan** [comment]
It might be an overhaul; so, yes!
