### ISSUE TITLE
Add Support for *.CR2, *.NEF and *.RAF File Extensions

### ISSUE THREAD

**Issue by EarthlingX** [lxqt/lximage-qt#188]
The previous LXDE Image Viewer had the skill to open and display CR2 file types (e.g. from Canon DSLR's). Could you add such a feature to LXImage as well?

##### System Information

* Distribution & Version: Debian 9 (Stretch)
* Kernel: 4.9.0-8-amd64
* Qt Version: 5 (?)
* libfm-qt Version: not installed
* libqtxdg Version: not installed
* lxqt-build-tools Version: not installed
* Package version: 0.5.1-1

Thank you very much for your efforts! :-)

**Comment by tsujan** [comment]
I can open `image/x-canon-cr2` with lximage-qt here.

lximage-qt opens all images supported by Qt. Probably, you don't have a complete Qt5 installation. Specifically, you need `qt5-imageformats` (or whatever name it has in your distro).

**Comment by agaida** [comment]
erm - veto :P - cr2 is not in the list of supported formats in qt5-image-formats-plugin

maybe some things are picked up from libraw, i read that they have an qt interface since some time.

**Comment by tsujan** [comment]
Anyway, it isn't an lximage-qt problem.

Moreover, his lximage-qt installation is very old.

**Comment by agaida** [comment]
Re Image formats - we should just use what qt proviedes - dunno the specs of the several raw formats - but i know a very good application that will fit for these tasks better than our simple image viewer. It's called nomacs - and it is in debian. If one want the current version one should switch to buster. Right now i don't care about backports - i guess i will do with the upcoming stable.
