### ISSUE TITLE
When deleting a Picture: Add Feature to auto-delete corresponding RAW File

### ISSUE THREAD

**Issue by EarthlingX** [lxqt/lximage-qt#189]
Assumed I have a folder with *.JPEG files beside of their belonging RAW files (e.g. *.CR2, *.NEF or *.RAF). The pairs all have the same file name, but with different file extension.

If I now delete a *.JPEG file (because it is unsharp for example), it would be a great feature if LXImage could provide an option to simultaneously delete the corresponding RAW file as well.

For example: Typical procedure - viewing images in the viewer and finding an unsharp image when watching them in fullscreen mode: Click the "Delete"-button on the keyboard and after deletion confirmation, LXImage will likewise delete the corresponding RAW file automatically.

##### System Information

* Distribution & Version: Debian 9 (Stretch)
* Kernel: 4.9.0-8-amd64
* Qt Version: 5 (?)
* libfm-qt Version: not installed
* libqtxdg Version: not installed
* lxqt-build-tools Version: not installed
* Package version: 0.5.1-1

Thank you very much for your efforts! :-)

**Comment by tsujan** [comment]
This is a very personal use case. Nothing else should be deleted on deleting X.
