### ISSUE TITLE
When viewing Images: Preserve current View Settings when moving on to next Image

### ISSUE THREAD

**Issue by EarthlingX** [lxqt/lximage-qt#190]
Assumed you are viewing an image in 100 % size to verify its sharpness. Afterwards you move on to the next picture to compare its sharpness with the first one.

Now it would be nice if the next picture could still be displayed in 100 % view size and in similar scrolled position of the previous image.

Maybe you could add an option with a checkmark to preserve position and view ratio for the following images? This button could be called "Comparison Mode" or something similar. When activated, the previous view size (e.g. 100 %), image position and viewed part of the image could be kept. With this it would be very easy to compare the sharpness between two images at a specific point.

##### System Information

* Distribution & Version: Debian 9 (Stretch)
* Kernel: 4.9.0-8-amd64
* Qt Version: 5 (?)
* libfm-qt Version: not installed
* libqtxdg Version: not installed
* lxqt-build-tools Version: not installed
* Package version: 0.5.1-1

Thank you very much for your efforts! :-)

**Comment by tsujan** [comment]
Will do it soon -- the lack of it is sometimes annoying: the app should keep the zoom state not only on going to the next/previous image but also on opening images. It needs a small GUI change.
