### ISSUE TITLE
Show the image size on status-bar

### ISSUE THREAD

**Issue by tsujan** [lxqt/lximage-qt#193]
It's a useful info the users want to know quickly.

Showing it on the title-bar isn't useful because it may be hidden inside the elided part. Actually, I think we should remove it from title-bar and put it on the status-bar.

Maybe, other useful info should be added to the status-bar too. As far as I see, it isn't used at all.

**Comment by glpzzz** [comment]
Perhaps we can add some  more information, like a Loading status on the left (transitory messages), image file size (kbs) on the righ next to image size...
