### ISSUE TITLE
add crop and resize 

### ISSUE THREAD

**Issue by bjlockie** [lxqt/lximage-qt#197]
It would be nice if this application could crop and resize an image.
I have been using The GIMP which is overkill  and is not a qt application.

**Comment by tsujan** [comment]
lximage-qt is and image viewer, not an image editor.

GIMP is the best tool for editing images. Krita was very nice before but now... I don't know; I prefer GIMP.

**Comment by tsujan** [comment]
> and is not a qt application

We use Qt in LXQt; that's far from adoring it.

**Comment by agaida** [comment]
For simple operations there is a damn fast alternative to gimp and krita -- nomacs
