### ISSUE TITLE
Support manpages

### ISSUE THREAD

**Issue by PanderMusubi** [lxqt/lximage-qt#202]
##### Expected Behavior
`man lximage-qt` would give manual

##### Current Behavior
not implemented

##### Possible Solution
fix this please

##### Steps to Reproduce (for bugs)
    man lximage-qt

##### System Information
* Package version: 0.7.0-2build2

**Comment by agaida** [comment]
If you want a man-page - just create one. We accept patches. For now lximage-qt is sufficient.
