### ISSUE TITLE
Automatically take screenshot and save without showing gui

### ISSUE THREAD

**Issue by PanderMusubi** [lxqt/lximage-qt#203]
Automatically take screenshot and save without showing gui

This requires the following command line arguments:
1. take screenshot, save and quit while not showing gui
2. capture whole screen (default) or only current window (will only work in combinatin with 1.)
3. do not include mouse pointer in capture (default) or do include (will only work in combinatin with 1.)
4. path to save taken screenshot (default to ~/Pictures/Screenshots with fall-back if that does not exists to ~/) (will only work in combinatin with 1.)
5. filename format (default Screenshot_%Y%m%d at %H%M%S-.png) (will only work in combinatin with 1.)

Benefits of implementing this, is that lximage-qt can be used more efficiently for taking screenshots as is currently possible in LXQt/Lubuntu.

##### System Information

* Package version: 0.7.0-2build2

**Comment by agaida** [comment]
We accept patches.

**Comment by agaida** [comment]
No reaction - so, screengrab can do this an is the long term solution

**Comment by PanderMusubi** [comment]
I'm working on other FOSS projects, so no patch from me. Nevetheless, the two issues are valid to be picked up by other contributors, I guess.

**Comment by tsujan** [comment]
@PanderMusubi PRs are always welcome. As @agaida implied, the focus is on screengrab for taking screenshots, lximage-qt's job being image viewing.
