### ISSUE TITLE
Images are blurry with scale 1.5

### ISSUE THREAD

**Issue by bosim** [lxqt/lximage-qt#242]
Images seem blurry when running with scaling, e.g.

    QT_FONT_DPI=96
    QT_SCALE_FACTOR=1.5

Maybe lximage-qt needs same fix as gwenview:
https://github.com/KDE/gwenview/commit/97e7de52276b46bc99b64117abfee0965e6f58e6

##### Expected Behavior

Crystal clear images

##### Current Behavior

Blurry images

##### Possible Solution

See above

##### Steps to Reproduce (for bugs)

1. QT_SCALE_FACTOR=1.5
2. lximage-qt
3. open an image and observe it is blurry

##### System Information

* Distribution & Version: Debian buster
* Kernel: 4.19
* Qt Version: 5.11
* libfm-qt Version: 
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
Good point!

But w have a bigger issue: https://github.com/lxqt/libqtxdg/issues/178

**Comment by tsujan** [comment]
I self-assigned because I fixed the problem here — waiting for https://github.com/lxqt/lximage-qt/pull/252 to be decided because of conflicting code lines.

**Comment by tsujan** [comment]
@bosim This branch has the fix: https://github.com/lxqt/lximage-qt/tree/hdpi

The PR is here: https://github.com/lxqt/lximage-qt/pull/257
