### ISSUE TITLE
Add an indicator when running as root

### ISSUE THREAD

**Issue by agaida** [lxqt/lximage-qt#246]
like in pcmanfm-qt

**Comment by tsujan** [comment]
OK. Later.

**Comment by glpzzz** [comment]
Which type of indicator?

**Comment by tsujan** [comment]
@glpzzz I'll do it later. The "Assignees" section is there to prevent duplicate work. If you see someone is assigned, you could skip the issue.

**Comment by tsujan** [comment]
Using an image viewer as root is unusual. Closing.
