### ISSUE TITLE
UI - use string "File" only for menu and not for menu item and toolbar icon too

### ISSUE THREAD

**Issue by p-bo** [lxqt/lximage-qt#265]
* Distribution & Version: Lubuntu 19.10 daily build

In process of translating (upstream Weblate) and testing how strings fits in their places noticed, that string "File" is used not only for File menu, but also for menu item in File menu and icon on toolbar.

Especially in File menu, simple File is a bit confusing - there should be "Open File" (the same for icon on toolbar).

So please, unlink string for menu item and icon from string for file menu and create new string (shared for menu item and toolbar icon) with content "Open File" (consistent with existing "Open Directory").

Thanks :)

![file-menu](https://user-images.githubusercontent.com/12208593/64732143-bff96200-d4e2-11e9-81e2-2bccfe16cc08.png)
![file-send](https://user-images.githubusercontent.com/12208593/64732145-c091f880-d4e2-11e9-8a64-67d9b666c412.png)

**Comment by agaida** [comment]
@p-bo  Nice catch - but unfortunately far to late :sunglasses:

Anyways: In such cases, please test latest upstream - if you don't know how to do it without much complications we can help.

![](https://i.imgur.com/8ZbcR9E.jpg)
