### ISSUE TITLE
Function to remove/disable "recently opened files";

### ISSUE THREAD

**Issue by Ub3rZ4cH** [lxqt/lximage-qt#270]
##### Expected Behavior
I would like to propose a way / option in Edit >> Preferences, to turn off/ disable "recently opened files", or some way to edit the config of the program to disable this feature?

##### Current Behavior
No way (that I can tell) to turn off "recently opened files".

##### Possible Solution
Impliment feature/ a way to remove / disable?

##### System Information
* Distribution & Version: Ubuntu (Lubuntu) 19.04 (Disco Dingo)
* Kernel: 5.0.0-31-generic
* Qt Version: 0.14.1

**Comment by tsujan** [comment]
Why?! Disabling a feature isn't always a feature.

**Comment by Ub3rZ4cH** [comment]
I was asking if possible to stop the recent files in anyway weather that be implemented as a feature or a configuration.

**Comment by tsujan** [comment]
It is possible but its being possible isn't enough: so far, no other user has wanted it.

**Comment by Ub3rZ4cH** [comment]
> It is possible but its being possible isn't enough: so far, no other user has wanted it.

Of course, I am not asking to impliment a feature based on just my recommendation! I was just requesting it, and weather or not it is already possible...
