### ISSUE TITLE
Add silent mode

### ISSUE THREAD

**Issue by glpzzz** [lxqt/lximage-qt#277]
##### Expected Behavior
After pressing a shortcut the screenshot is taken in some of the 3 modes and then saved as a file or to clipboard

##### Current Behavior
The screenshot is shown and the user have to decide what to do with it. Not good for silent behavior or a more straighforward one (copy to clipboard to paste in IM app)

##### Possible Solution
Add more options to the current --screenshot one: --screenshot-full, --screenshot-window, --screenshot-region. More options to for clipboard and autosave, if not set, open the screenshot (current)

**Comment by tsujan** [comment]
LXQt's screenshot utility is [screengrab](https://github.com/lxqt/screengrab). lximage-qt is an image viewer with some additional functionalities and there is no plan to make them fully-fledged.
