### ISSUE TITLE
Minimal GUI

### ISSUE THREAD

**Issue by glpzzz** [lxqt/lximage-qt#283]
This is something I did for my self perhaps is interesting for everyone. I like image viewers with minimal GUI, as sxiv, so I did this changes to my local lximage-qt

##### Expected Behavior
Ability to hide all toolbars, menubar and status bar,  and the program remembers this behavior between executions.

##### Current Behavior
The annotations toolbar can be hidden, the main toolbar too but not from view menu, just with right click in toolbars area. Also nor the menu nor the status bar can be hidden. Just in fullscreen status

##### Possible Solution
I replicated what is done with the annotations toolbar for the others

##### Context
This is just taste thing. I like this way and perhaps other users too. It can be done in fullscreen mode but fullscreen is not working if you can keep the other windows in the same view.

**Comment by tsujan** [comment]
There's no need to add a menu-item for it. Please add a "Compact mode" to Preferences instead and make a pull request (PR)! In that way, your goal will be achieved without cluttering the GUI.

**Comment by glpzzz** [comment]
And there is a menu item for annotations. And in other lxqt apps like lxqt-archiver there is a toggle  visibility option for every bar in the view menu. 

But I like the compact mode idea

**Comment by glpzzz** [comment]
Also added Tab as shortcut por compact interface mode.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/lximage-qt/commit/e3a4788d82e541f8e6e57a40342db3e5741e8d52, https://github.com/lxqt/lximage-qt/commit/7d5ba9c910d5038251e1b26d5ff3cb4691f03b7d and some other commits.

**Comment by stefonarch** [comment]
Give me a call when all is over, to update translations ;)

**Comment by tsujan** [comment]
Sure.

**Comment by tsujan** [comment]
@stefonarch 
It isn't finished yet but I don't think it'll be finished soon. You could update translations if you think an update is needed, knowing that it should be followed by another update later.
