### ISSUE TITLE
Add crop feature to LXImage-Qt

### ISSUE THREAD

**Issue by kenfallon** [lxqt/lximage-qt#288]
##### Expected Behavior

There should be a **crop** feature.

##### Current Behavior

There is no **crop** feature.

##### Steps to Reproduce (for bugs)

1. N//A

##### Context

The most common action for me at least is to send in a smaller portion of the image. It would be great to have this included as an option.

##### System Information

* Distribution & Version: Fedora release 30 (Thirty)
* Kernel: Linux 5.3.8-200.fc30.x86_64 x86_64 x86_64 x86_64 GNU/Linux
* Qt Version: 5.12.5
* libfm-qt Version: 0.14.1
* libqtxdg Version: 3.3.1
* lxqt-build-tools Version: 0.6.0
* Package version: 0.14.1

**Comment by tsujan** [comment]
I'm not sure if it's a good idea to add image editing functionalities to an image viewer but cropping seems reasonable because it isn't more complex than rotation or flipping -- although, I don't mean that on the code level.

**Comment by agaida** [comment]
@tsujan - we should think about - cropping is very elementry - i try to describe a use case:
* one have n pictures and check them back in a row - which very basic functionality comes to mind, what will make this guy really happy? 
* cropping maybe
* contrast etc
* numbering as in screengrab
* somethings i forget right now

**Comment by tsujan** [comment]
Yes, image editing functionalities aren't for an image viewer.

**Comment by agaida** [comment]
please have a short test of `flameshot` - cool functionality for a screengrabber - not what i would like for LXQt, but kind of impressive. And i know we could do some of this and better

**Comment by tsujan** [comment]
Hadn't heard of it. But Arch/Manjaro is so cool: `sudo pacman -S flameshot`, then `flameshot`.

Frankly, IMO it's counter-intuitive and bloated. I prefer screengrab: simple and efficient.

**Comment by agaida** [comment]
dependend of the use case - a very good friend and co-leader of siduction is journalist. He write about hard- and software world wide. Flameshot do basically all the things he need. We don't.

Short:
* he can do snapshots and blur sensitive things out before making the screenshot
* he can add a line of text - or two before he press the button
* he can add some arrows to point out what he means - in combinition with the text

ok, i don't want this in lximage-qt - but i want to be able to take a certain serie of screenshots, have a look in lxqtimage and do the dirty work in a editor of my choice.  
and to be honest - most of the screenies with arrows and a line of text was taken with flameshot - the "only" disadvantage of flameshot right now is: delayed shots are not easily possible, perhaps they have the same discussions as we now. 

Another point: nothing  from the things pointed above are really needed. But some of them would ease the users life.

**Comment by agaida** [comment]
erm - and i forget: not all things should or has to be implemented in screengrab or lximage-qt - but it should be possible to have such an workflow as described easily.

**Comment by tsujan** [comment]
First, let's close this because lximage-qt isn't an image editor. Rotating/flipping is sometimes *needed for viewing an image*, but cropping isn't. (Annotation was merged by mistake.) Adding the "enhancement" label was my mistake.

My opinion about Flameshot: I don't use it because I want a fast and easy-to-use screenshot utility like screengrab, not a multi-purpose app. If I want to add arrows to a screenshot, I'll use GIMP because I could do the job without limitation -- I even won't use the buggy Annotation toolbar of lximage-qt. I also use GIMP for other kinds of image editing.

Moreover, adding image editing functionalities isn't a piece of cake (cropping code can be quite complex, for example). It can add bugs to an app, while it wasn't really needed in the first place (see lximage-qt's annotations).

So, IMHO, it's better to focus on image viewing with an image viewer and on taking screenshots with a screenshot utility. After all, don't we want to remove lximage-qt's screenshot code because...?

**Comment by agaida** [comment]
no problems right now - but in this case we should maybe refine some functionality later. Maybe it would be a good idea to think about some kind of plugin structure :D 

Please take my opinion with a good  grain of salt - we was in the functionality discussions before ;P

**Comment by tsujan** [comment]
You may not believe it that I liked EOG when I was a gnome2 user. lximage-qt is much better than EOG and is still uncluttered (again, apart from annotations). There are some image viewing functionalities that should be added to it (I haven't forgotten https://github.com/lxqt/lximage-qt/issues/192) and some bugs that should be fixed (I found one during our discussion).

I really prefer an app that does its job fully and correctly to an app that does various jobs but incompletely and sometimes incorrectly. That's my humble opinion and I won't tear out my hair if lximage-qt becomes the latter.

**Comment by Chiitoo** [comment]
Forgot to add, that one reason to why I tend to not use the thumbnail feature (especially just for "Open With...", is the fact that the thumbnails need to be created, and it will lead to sometimes having tens of thousands of small images that serve no purpose under '$HOME/.cache/thumbnails/normal'.

I think something like 'delete thumbnails on exit' might amend that, though they're still being created.

I also wonder if it's related to PCManFM-Qt, that when saving files via, say, Falkon, thumbnails are also created even though the setting for showing thumbnails is off in PCManFM-Qt.  I never remembered to look more into that.  Anyblue, that's also for another issue.

**Comment by tsujan** [comment]
BTW, a plugin structure is a great idea. It's also good for pcmafm-qt. I, for one, have no idea how to implement it.

**Comment by agaida** [comment]
it was only an idea  - and to your surprise i prefer a very clean and tidy implementation as long we don't have a kind of plugin structure ready - but again - may not be now, but later ... :dagger: 

PS: if you don't have a clue about a plugin structure - how should or could i have? :)

**Comment by tsujan** [comment]
> if you don't have a clue about a plugin structure

I've never written an app with plugins  :) Might try it at some point.
