### ISSUE TITLE
[Feature Request] Edit shortcuts for full screen

### ISSUE THREAD

**Issue by Jzarecta** [lxqt/lximage-qt#293]
##### Expected Behavior

Would love to change F11 to F for full screen. 

##### Current Behavior

Preference doesnt have a shortcut menu or have an alternate shortcut for F11/F.

##### Possible Solution

Add a shortcut menu to change behaviors.

##### Steps to Reproduce (for bugs)

1.  Go to Settings -> Configure Shorcut.
2.  Add alternate shortcuts.
3. 
4. 

##### Context

Graphical tools like Gwenview also use F for full screen or as Alternate shortcut. 

##### System Information

* Distribution & Version:  Archlinux
* Kernel:  4.11
* Qt Version:  5
* libfm-qt Version: 
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
At some point, a shortcut editor will be added.

**Comment by tsujan** [comment]
Started to add a shortcut editor:

![shortcuts](https://user-images.githubusercontent.com/981076/71608960-e62e3500-2b99-11ea-8f5b-2e0b03d46d27.png)

Will make a PR when the code is polished and tested.

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/lximage-qt/pull/296. I think its code could be used like a template for other apps too.
