### ISSUE TITLE
Drop Maximization on open gif

### ISSUE THREAD

**Issue by TrueCat17** [lxqt/lximage-qt#301]
On open gif-file (not animated too) viewer's window drops param "to maximazed"  
After all images shown with them real size, until window will be maximazed manually

(if open image in other format and press Left/Right to switch on gif - all ok)

* Distribution & Version: Debian 11 (Bullseye, unstable, Sid)
* Kernel: 5.2
* Qt Version: 5.12.5
* libfm-qt Version: libfm-qt6 ver. 0.14.1-12
* lxqt-build-tools Version: in repo 0.6.0-2

**Comment by tsujan** [comment]
I didn't understand the English -- not a single sentence. Please be more specific by describing the issue in a step-by-step and reproducible way.

Please note: If you filled in the issue template, your report might be understandable.

**Comment by TrueCat17** [comment]
Sorry, but I think, I make not bad description

1. Open, for example, PNG-image
2. Maximaze window (not resize, not fullscreen, button to maximazed near with button to close window: [_][O][X] - second)
3. Close viewer
4. Open prev image again - window of viewer will be maximazed
5. Close again
6. Open GIF-image
7. Window not maximazed - bug (!)

**Comment by tsujan** [comment]
> Sorry, but I think, I make not bad description

You did but your second description is quite good. Please try to make your future reports like it. Thanks in advance.

It shows there is a discrepancy in opening gif/SVG images, on the one hand, and PNG/JPG ones, on the other hand.
