### ISSUE TITLE
Drawing tools don't work

### ISSUE THREAD

**Issue by jimgreen2013** [lxqt/lximage-qt#307]
##### Expected Behavior
draw a rectange or a circle

##### Current Behavior
can't draw a circle, nothing happened

##### Possible Solution
i check the system log with journalctl, there is some log like:
```bash
Apr 13 09:58:55 miPad lximage-qt[12057]: QCoreApplication::postEvent: Unexpected null receiver
```
Maybe there is a null pointer

##### System Information
* Distribution & Version: Fedora 31
* Kernel: 5.4.15
* Qt Version: 5.13.2
* libfm-qt Version: 
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version: 0.14.1

**Comment by Chiitoo** [comment]
Had a user report this a while ago, and I noticed things are actually drawn, sort of, just not shown.

If you save the file, they appear in the saved image.

**Comment by tsujan** [comment]
As I mentioned elsewhere (sorry, don't have time to find where), the drawing tools were merged by mistake. IMO, lximage-qt shouldn't do image editing. I wanted to remove them but some users told me not to. So, I disabled them by default in git (the user can re-enable them).

In short, *the drawing tools have several bugs* and, until now, no one has had time to fix them.

**Comment by jimgreen2013** [comment]
@Chiitoo thanks for your reply.
@tsujan totally understand what you're talking about, besides i am big fan of [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy)
> do one thing and do it better

however, consider a situation when you want a drawing tools, without an image viewer, you can't even find the right place to draw. So in my opinion, you shouldn't remove it.
And drawing tools is really very helpful in my work when i communicate with my colleagues via IM app.
Maybe i can try to look into the code and find what cause the bug, but not confident, because i'm not familiar lximage or lxqt code

**Comment by tsujan** [comment]
> So in my opinion, you shouldn't remove it.

I won't.

I've found serious problems in its code but haven't found time to fix them, being busy with other codes. Its coder was working on it and I was reviewing his work it but we merged it by mistake. Since then, he hasn't touched it.

> Maybe i can try to look into the code...

Yes, please!

**Comment by jimgreen2013** [comment]
@tsujan I think i have found the reason for this bug, according to the qt documentation:
> Warning: When the paintdevice is a widget, QPainter can only be used inside a paintEvent() function or in a function called by paintEvent().

`QGraphicsView` is a widget, so QPainter should be used in the paintEvent(), not the mouseReleaseEvent().

Based on the current code in paintEvent(). If i zoom in the picture, then draw a rectangle, the rectangle will show.

**Comment by tsujan** [comment]
Good. You could make a PR if you've found a problem and its solution.

The lack of undo/redo are disappearance of annotations with rotation are also important issues. But one issue at a time.

**Comment by jimgreen2013** [comment]
@tsujan 
i find it's more complicated to fix this bug than i have thought, i need your help and advices

## Background
1. why doesn't the drawing rectangle show?
according to the [qt documentation](https://doc.qt.io/qt-5/qpainter.html#details):
> Warning: When the paintdevice is a widget, QPainter can only be used inside a paintEvent() function or in a function called by paintEvent().

Now the `QPainter` is called by the `mouseReleaseEvent()`, so the drawing rectangle don't show

2. why does the drawing rectangle show in the saved image?

we have drawn the rectangle in the image properly, so you can see it in the saved image

3. why does the rectangle show when the image is scaled

`ImageView` override the `paintEvent()`, when the image is scaled, `paintEvent()` is triggered, we will paint the scaled image in the `paintEvent()`, so it works well

## Possible solutions 
1. call the `QPainter` by `paintEvent()`

This solution is so straightforward, but it's impossible.Why?
the `paintEvent()` needs to be triggered by calling `update()` function, but this is not the case in `QGraphicsView`: **`update()` will not trigger `paintEvent()` in QGraphicsView**.
According to the [Qt Qwidget Documentation](https://doc.qt.io/qt-5/qwidget.html#custom-widgets-and-painting)

> Since QWidget is a subclass of QPaintDevice, subclasses can be used to display custom content that is composed using a series of painting operations with an instance of the QPainter class. This approach contrasts with the canvas-style approach used by the Graphics View Framework where items are added to a scene by the application and are rendered by the framework itself. 

2. **Only** Use `QGraphicsRectItem *QGraphicsScene::addRect`

sample code:
```c++
void ImageView::mouseReleaseEvent(QMouseEvent* event) {
  QPoint endPoint = mapToScene(event->pos()).toPoint();
  scene_->addRect(QRect(startPoint, endPoint)); 
}
```
we create a `QGraphicsRectItem` that overlap the original image.
**pros**:
* easy to undo

**cons**
* the original image doesn't really change, when saving the image, we need to paint the rectangle on the original image
* Besides painting scaled image in `QPaintEvent()`, we should also paint the scaled rectangle

3. Use `QGraphicsRectItem *QGraphicsScene::addRect` and drawing on the original image at the same time

sample code:
```c++
void ImageView::mouseReleaseEvent(QMouseEvent* event) {
  QPoint endPoint = mapToScene(event->pos()).toPoint();
  scene_->addRect(QRect(startPoint, endPoint));

  QPainter painter(&image_);
  painter.drawRect(QRect(startPoint, endPoint)); 
}
```
**pros**
* save image keeps unchanged
* `paintEvent()` keeps unchanged

**cons**
* not easy to undo

## Do we still need the cached scaled image in 2020?
i check the git log, find this:
```bash
commit 77bd1dd8ca7e0b2d57532d4d7e2071e2587e337b
Author: Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
Date:   2014-03-18 01:32:31

    Create a cache for the high-quality scaled image of the currently viewport and use it to override the default paintEvent() of QGraphicsView as needed.
    This improves the image quality a lot when we scale down large photos.
```
the cached scaled image make the source code a litter bit complicated.

i make an experiment, i see no difference between the *cached scaled image*(pic1.jpg) produced by lximage and the scaled image(pic2.jpg) produced by  the Graphics View Framework.

* pic1
![pic1](https://user-images.githubusercontent.com/15890793/81500965-28197580-9308-11ea-8a93-a9b85e225fb5.jpg)

* pic2
![pic2](https://user-images.githubusercontent.com/15890793/81500966-2d76c000-9308-11ea-836f-32942792b9ff.jpg)

* original large size image
![taylor-swift-red-lip](https://user-images.githubusercontent.com/15890793/81500970-3071b080-9308-11ea-8006-abb235bb1847.jpg)

**Comment by tsujan** [comment]
@jimgreen2013 I haven't had time to look into it and, probably, won't in near future, being busy with many projects. In short, if no other dev does it, you'll be alone. But if you make a PR that really solves the problem, I'll review your code.

> Do we still need the cached scaled image in 2020?

Please don't remove anything from the main code because of this. The year isn't relevant.

**Comment by jimgreen2013** [comment]
@tsujan that's ok, i see, i'll make a PR without changing too many current code~

**Comment by tsujan** [comment]
Fixed in https://github.com/lxqt/lximage-qt/commit/e6e0fc9a86758659efd802e1b467d40fefaf4750
