### ISSUE TITLE
setting screenshot defaults

### ISSUE THREAD

**Issue by chri2** [lxqt/lximage-qt#308]
Great program - thanks! I like the screenshot function that shows the screenshot immediately a lot.

It would be great if there would be a way to set defaults for the screenshot for the area mode, what to include and the timer.

Even saving the settings from the last screenshot to be restored the next time the screenshot function is called would be a great help!

**Comment by tsujan** [comment]
Please use [Screengrab](https://github.com/lxqt/screengrab) for taking screenshots. The screenshot code of lximage-qt will be removed sooner or later and we don't want to add to it.
