### ISSUE TITLE
dual screen problems

### ISSUE THREAD

**Issue by chri2** [lxqt/lximage-qt#309]
When capturing an area selected with the mouse it is not possible to capture parts of one of two displays used.

Debian Buster, xorg, dual screen configuration - side by side: left screen internal notebook screen, right screen external monitor.

When trying to capture choosing an area with the mouse about the right half of the right screen is missing and cannot be selected.

This picture shows the screen layout:

![screens](https://user-images.githubusercontent.com/15866990/79726425-4c220200-82da-11ea-841b-82f5bbdbce71.jpg)

This picture shows what is presented when trying to select the capture area with the mouse:

![capturing_area](https://user-images.githubusercontent.com/15866990/79726499-6c51c100-82da-11ea-8e2a-bda8fd750217.jpg)

The right part of the right screen is missing.

The area above the left screen (which is smaller than the right one) seems to be always filled with parts of the first desktop. Confusing, but not really a problem.

**Comment by tsujan** [comment]
See https://github.com/lxqt/lximage-qt/issues/308#issuecomment-616533912
