### ISSUE TITLE
inconsistent arrow usage

### ISSUE THREAD

**Issue by pirate486743186** [lxqt/lximage-qt#313]
##### Expected Behavior

When you use the arrows, all of them should either move the image (if not fitted), or change image.

##### Current Behavior

When the image is not fitted:
1.arrows up and down move the image.
2.arrows left and right change the image.
 
##### Possible Solution

when the image is fitted, the arrows should change images. Including up and down. 
when not fitted, the arrows should move the image, only.

##### Steps to Reproduce (for bugs)

1. just have an image that is not fitted.
2. play with the arrows.

##### Context

The arrows shouldn't be inconsistent like that. It's clearly a bug.

##### System Information

i actually didn't install the latest version. 
* Distribution & Version: ubuntu 20.04
* libfm-qt Version: 0.14.1

**Comment by tsujan** [comment]
> when the image is fitted, the arrows should change images. Including up and down.

Take a look at the thumbnail view: it's only a row; no column. Up/Down arrows shouldn't switch the image.

Moving the image is done by `Alt+Up/Down/Left/right`. Since Up/Down has no other function, it's natural to allow them to move the image upward/downward.

**Comment by pirate486743186** [comment]
-_-... kernel developers designing a UI...
So, the program is fine. The flaw is in the choice of the default shortcuts.

Most people don't know about Alt+arrows. More so, since the shortcut editor was added only recently. It's still the case, that you are mixing moving the image with changing images. You shouldn't do that with the defaults.

**Comment by tsujan** [comment]
> The flaw is in the choice of the default shortcuts.

They aren't shortcuts -- let alone default shortcuts -- but Qt's default behavior. lximage-qt has no shortcut to move big images.

It's so simple: Get the latest version and assign Up/Down to Next/Previous file (besides the hard-coded Right/Left) if you want.

**Comment by pirate486743186** [comment]
i'm just trying to report a small bug.

This is actually a bad UI design decision.
Exactly what up and down are doing doesn't matter.

Most users, will simply see up/down move the image, and left/right change image. They will not be aware of the wider context you are talking about and simply find it nonsensical.

If you expect that the users are meant to go read the manual, then yes, that's a bad design decision.

The arrows should be consistent. Either up/down also change images, either they do nothing, either all the arrows move the image and changing images is done by something else .... You see? something self consistent....

do what you want....

**Comment by tsujan** [comment]
If you can't take "no" for an answer, please don't waste our time with longwinded comments.

**Comment by pirate486743186** [comment]
@PCMan 

hello PCMan. I have a minor disagreement with Tsujan about the arrow keys in lximage-qt. He decided, that when the image is not fitted, left and right change the image, while up and down move the image. That's crazy, no one else does that. I'm arguing, that the arrows should be doing one or the other, but not half one and half the other....
