### ISSUE TITLE
Command line options for what to screenshot

### ISSUE THREAD

**Issue by probonopd** [lxqt/lximage-qt#334]
Would a PR be welcome that would add command line options?

```
-w, --whole-screen: Capture whole screen
-v, --current-window: Capture current window only
-q, --area: Capture an area of the screen
-m, --mouse: Include mouse cursor
```

Using one of the first three would result in the dialog window to be skipped that appears when one uses `-s, --screenshot`.

This feature would be especially useful for setting keyboard shortcuts like Alt-Shift-3 to take a screenshot.

**Comment by tsujan** [comment]
For a long time, we've had a plan to remove the screenshot functionality from lximage-qt (I didn't agree at first but later, I was convinced that it would be the correct thing to do). The reason is that LXQt's screenshot utility is screengrab and we don't want the current X11 code. That will happen sooner or later. So, nothing related to screenshots should be added to the code..

**Comment by tsujan** [comment]
@yan12125, @luis-pereira, @jubalh 
When is the appropriate time to remove the screenshot codes from lximage-qt? Before 0.16 or after it?

**Comment by probonopd** [comment]
Sorry, didn't know that. Was assuming this was the tool for screenshots since my LXQt installation came with it preconfigured.

**Comment by tsujan** [comment]
> Sorry, didn't know that.

That's understandable. Finding the discussion page isn't easy.

We need a way to prevent confusion when the screenshot functionality is removed -- probably a message box that says, "Please use Screengrab to take screenshots." Or, perhaps, it's better to add the message as a waring bar to V0.16 and to remove the screenshot code only in 0.17, when a working upload functionality is added to Screengrab?

**Comment by yan12125** [comment]
+1 for give a warning in 0.16 and remove in 0.17. Don't remove it without a warning.

**Comment by tsujan** [comment]
> Don't remove it without a warning.

Right. There's no haste.

Yes another possibility is keeping the code, adding a compilation option for the screenshot and turning it off by default.

**Comment by probonopd** [comment]
To be less intrustive, just printing a warning in the usage statement of the command line arguments for screenshots might be sufficient (at least I would have seen it there).

**Comment by tsujan** [comment]
@probonopd, would you make a PR the command-line part?

**Comment by probonopd** [comment]
@tsujan sent

**Comment by tsujan** [comment]
@probonopd, thanks! It's merged now.

What remains to do:
 * Either adding a compilation option that's off by default or adding a warning bar somewhere (a messagebox would be intrusive). This needs to be decided by members and contributors.
 * Perhaps, adding something like the `-d` option to Screengrab.

**Comment by J-Dunn** [comment]
I came across this while looking for how to configure the default option for a screen shot with lximage-qt --screenshot

This utility is nice and simple and has the basic functionality I need but is a PITA to have to click the 'capture an area of the screen' option every darn time I use it. (This is invariably what I need to do). 

I was expecting a line in a config file in ~/.config/lximage-qt somewhere, but this conversation suggests it does not exist. 

Is there really no way to set this in advance ?
