### ISSUE TITLE
Please add keyboard shortcut for clipboard

### ISSUE THREAD

**Issue by kanliot** [lxqt/lximage-qt#341]
lximage-qt would be a better program if I could use the "copy image to clipboard" underneath the edit menu with "Control+c" instead of the current keyboard shortcuts. 
Right now I use the keyboard to go through the edit menu.  I think this "copy image to clipboard" deserves a keyboard shortcut just for that function. 

This would not speed my work up very much, but it would feel very nice. 
Thank you.

**Comment by tsujan** [comment]
Add a any shortcut in Preferences → Shortcuts

**Comment by kanliot** [comment]
ok sorry 

 I was running on an very old version of lximage-qt
