### ISSUE TITLE
Ctrl-C, Ctrl-V do not work

### ISSUE THREAD

**Issue by probonopd** [lxqt/lximage-qt#364]
##### Expected Behavior

- Ctrl-C (or whatever the system default shortcut is) copies to the clipboard
- Ctrl-V (or whatever the system default shortcut is) pastes from the clipboard

##### Current Behavior

Copy and paste are lacking their usual system default shortcuts

![image](https://user-images.githubusercontent.com/2480569/100006475-d54a6b80-2dca-11eb-97f7-73edf265bf32.png)

##### Possible Solution

Add system-wide default shortcuts

##### Steps to Reproduce (for bugs)

Download and boot the [hello Live ISO](https://github.com/helloSystem/ISO/releases/tag/continuous-hello), open lximage-qt

##### System Information

* Distribution & Version: FreeBSD (helloSystem)
* Kernel: 1202000
* Qt Version: 5.15.0
* libfm-qt Version: 0.15.0
* libqtxdg Version: 3.5.0
* lxqt-build-tools Version: ?
* Package version: 0.15.0

**Comment by tsujan** [comment]
The app has a shortcut manager.

**Comment by probonopd** [comment]
Thanks, but why not make Ctrl-C and Ctrl-V the default, as in practically all other applications?

**Comment by tsujan** [comment]
When an app has a shortcut editor, it doesn't make a difference. And your version is old; lximage-qt also has "Copy Path".
