### ISSUE TITLE
An option to enforce fitting on showing next image

### ISSUE THREAD

**Issue by adjamhub** [lxqt/lximage-qt#380]
IF you show an image from an image dir, zoom it (in or out) then move to next one, zoom settings are preserved instead of reloading initial ones (original vs fit). I don't think this is the expected behavior. You can notice it a lot if you zoom in at max an image and then go to the next one.

##### Expected Behavior

If you like fitting your images, every image you load should be fitted regardless of the zoom (in or out) you did in the previous image.

##### Current Behavior

zoom settings are preserved when moving to a new image

##### Possible Solution

An option in the settings to show new images with zoom to original/zoom to fit settings.
I can work on it if you like the idea.

**Comment by stefonarch** [comment]
> I can work on it if you like the idea.

I would like it, the zoom in is used usually to see details in one image only.

**Comment by tsujan** [comment]
> I don't think this is the expected behavior

It is. The zoom factor and fitting state are both remembered. What you want would be a bug to fix, not a feature.

> If you like fitting your images, every image you load should be fitted

If you like fitting your images, toggle the "Fit" item; then, all images will be fit.

**Comment by tsujan** [comment]
> the zoom in is used usually to see details in one image only.

No! It depends on what the user wants to do. Ignoring the zoom factor and fitting the next image would be annoying (= bug).

If the user wants to see the next images fit to the window, he/she could simple toggle the Fit item (by using its shortcut). We shouldn't force that.

**Comment by stefonarch** [comment]
Well, I disagree here.
 I'm a appassionate photographer and if this setting would exist I would activate it immediately. If you go trough a collection you will zoom and move in one image only and every next image you have to reset it.

**Comment by adjamhub** [comment]
Well... I really think "what user wants" is to normally fit the next image. Gwenview does so. Eog does. Lximage-qt does not.
Using your words, if the user wanna zoom also the next image, he/she could simply toggle the zoom item. You should'nt force that.

**Comment by tsujan** [comment]
> Well... I really think "what user wants" is to normally fit the next image

You could assign `F` or any other shortcut to the Fit action for your special use case but please don't generalize it as a "problem".

Listing the names of some apps and thinking they should show a standard is a bad, repetitious argument.

> Using your words, if the user wanna zoom also the next image, he/she could simply toggle the zoom

I didn't get what you meant but, put clearly and simply, the current behavior just amounts to this: *If the user chooses an action, it'll persist until he chooses another action. No action will be enforced on him.*

**Comment by tsujan** [comment]
> I'm a appassionate photographer and if this setting would exist I would activate it immediately.

Assign `F` and press it immediately ;)

Consider a user who wants to see the details of icons, as a counterexample of your use case. Please don't say, "Who does that?" The good thing is that we don't enforce anything (see my previous comment).

**Comment by adjamhub** [comment]
I can change my proposal merging the 2 ideas: I can work adding an option to use last zoom settings or force zooming to fit on the next image. having the first one as default will preserve actual behavior. Setting the second one will zoom to fit every image loaded.
Is it ok?

**Comment by tsujan** [comment]
That's completely acceptable :) Please do it!

**Comment by tsujan** [comment]
I changed the title and reopened the page.
