### ISSUE TITLE
Option to disable smoothing filter for zoom in/out

### ISSUE THREAD

**Issue by kovec681** [lxqt/lximage-qt#386]
There should be an option in the preferences to disable the smoothing/blur filter when zooming in on images.

##### Expected Behavior

Allow the user to disable the filter that adds a blur/smoothing effect when scaling an image.

##### Current Behavior

The smooth/blur filter is always enabled when the scale is not 100%.

##### Possible Solution

Add an option to the Preferences menu.

##### Context

I work with pixel art and always need to zoom in to check individual pixels. The filter that blurs the image means it's impossible to use this image viewer and i need to install a different one.

##### System Information

* Distribution & Version: Ubuntu 20.10
* Kernel: Linux  5.8.0-33-generic
* Qt Version: 5.14.2
* libfm-qt Version: 0.15.1-0ubuntu3
* libqtxdg Version: not installed
* lxqt-build-tools Version: not installed
* Package version: 0.15.0-0ubuntu1

**Comment by tsujan** [comment]
Acceptable. But only when the image is zoomed in.

For a zoom-out, the lack of smoothing would have no value (the image at right):

![zoom-out](https://user-images.githubusercontent.com/981076/104778326-6a962a80-5792-11eb-9f3e-873844ce3954.png)

**Comment by kovec681** [comment]
It could be 2 separate options for zoom in and zoom out and let the user decide. I was on a Debian machine with MATE earlier today that had options for both though i don't remember which viewer it was... perhaps Eye of MATE Image Viewer?

**Comment by Chiitoo** [comment]
I've been meaning to do this for ages, but never got to it still!

Any pointers on how to go about it would be most appreciated (though I imagine someone else will get it done before I ever get to it).

Thanks for suggesting this!

**Comment by tsujan** [comment]
> Any pointers on how to go about it

If I correctly remember, it should be enough to return the default paint event in `ImageView::paintEvent` (without using cache).

**Comment by tsujan** [comment]
> (though I imagine someone else will get it done before I ever get to it)

If you mean me, I won't have time for it soon. A PR would be appreciated.
