### ISSUE TITLE
Delay by default before capturing a screenshot

### ISSUE THREAD

**Issue by grahamperrin** [lxqt/lximage-qt#392]
##### Expected Behavior

1. Capture a shot
2. use the File menu of Image Viewer to capture another
3. click OK
4. an opportunity to hide the Image Viewer window

##### Current Behavior

4. a shot that includes the previous shot

##### Possible Solution

Don't default to 0 (zero) seconds. 

##### Context

https://github.com/helloSystem/Utilities/issues/39

> … I prefer a delay of five seconds, the preference should be remembered. …

##### System Information

helloSystem `0.4.0 (0D26)`

**Comment by stefonarch** [comment]
https://github.com/lxqt/lximage-qt/blob/master/src/application.cpp/#L105
Screenshot functionality will be removed at some point.
https://github.com/lxqt/screengrab/issues/42

This said I wonder why I cannot find anywhere in the GUI the `Take a screenshot (deprecated, please use screengrab instead)`

**Comment by tsujan** [comment]
Yes, please use Screengrab to take screenshots. lximage-qt is an mage editor.

**Comment by grahamperrin** [comment]
### Image Viewer

https://github.com/lxqt/lximage-qt/issues/392#issuecomment-773264874

`lximage-qt --help` deprecation noted and understood, thank you. 

For reference, **Capture Screenshot** is in the File menu: 

![image](https://user-images.githubusercontent.com/192271/106939716-87ca7300-6718-11eb-9213-c8e0fbfd2f3a.png)

### ScreenGrab

Re: https://github.com/helloSystem/Utilities/issues/39#issuecomment-773518844 unless I'm missing something, ScreenGrab is not ported to FreeBSD. I'll check with the maintainer of `x11-wm/lxqt`.

**Comment by stefonarch** [comment]
Yeah it's there until it will be removed. 
It doesn't make sense to add a warning there IMHO as far as it works.
