### ISSUE TITLE
screenshot QT_SCALE_FACTOR<>1

### ISSUE THREAD

**Issue by bosim** [lxqt/lximage-qt#402]
##### Expected Behavior

Screenshot selection should be one-to-one with display

##### Current Behavior

There is a large empty area and selection is relatively increased.

##### Possible Solution

Seems like the coordinate handling is not taking the scale factor into account (is my guess)

##### Steps to Reproduce (for bugs)

1. Use e.g. QT_SCALE_FACTOR=1.5
2. Run `lximage-qt -s`
3. Select "Capture an area of the screen"
4. Things will look strange

##### Context

screengrab works as expected

##### System Information

* Distribution & Version: Debian bullseye
* Kernel: 5.10.0
* Qt Version: 5.15.2
* libfm-qt Version: -
* libqtxdg Version: -
* lxqt-build-tools Version: - 
* Package version:  -

**Comment by tsujan** [comment]
lximage-qt's screenshot is deprecated and will be removed at some point. See `lximage-qt --help` if you have a recent version.

**Comment by bosim** [comment]
ah didn't notice, thanks!

**Comment by tsujan** [comment]
Use screengrab. It should be OK with scale factors > 1.
