### ISSUE TITLE
Please add some annotation tools to do minimal edit to image (like arrow, lines, text, boxes)

### ISSUE THREAD

**Issue by gsitreble2019** [lxqt/lximage-qt#410]
##### Expected Behavior
Feature request: After making a screenshot many times users share it to tell something. Like see this in GUI like arrow or box or text or to file bugs 

##### Current Behavior
Would be great to do some basic things like arrow/box/hide-data before sharing image.

##### Possible Solution

See for example gnome-shutter tools (https://shutter-project.org/) or use online tools like https://szoter.com/launch/

##### Context

Yes. Just try to explain how to do some thing for another person. 

##### System Information
All versions of lximage-qt

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* libfm-qt Version: 
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
Was added a long time ago.

NOTE: lximage-qt is neither for taking screenshots nor for image editing.
