### ISSUE TITLE
Add ability to rename files

### ISSUE THREAD

**Issue by xiota** [lxqt/lximage-qt#445]
Would be nice to be able to rename images.  `libfm-qt` has a rename dialog that could be used, but I don't know how.  Is there any example code that shows how to use the dialog?  I also don't know the meaning of the arguments and how to get from `FilePath` (`currentFile_` in lximage-qt)  to the `FileInfo` needed by the dialog.

    explicit RenameDialog(const FileInfo &src, const FileInfo &dest, QWidget* parent = nullptr, Qt::WindowFlags f = Qt::WindowFlags());

**Comment by tsujan** [comment]
Images can already be renamed both in the thumbnail view and also in File Properties.

If you mean renaming multiple images together, that's not the job of an image viewer.

**Comment by xiota** [comment]
I didn't know right clicking on the thumbnails had a different context menu than the main image.  How do I assign a shortcut to the rename function?

**Comment by tsujan** [comment]
By assigning a shortcut to File Properties.
