### ISSUE TITLE
Context menu in thumbnail bar: not working items

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lximage-qt#466]
Clicking an empty space in thumbnail bar the context menu is displayed as in pcmanfm-qt, also eventual custom actions (here "disk usage" with filelight). Some of them are not working and should be greyed out or fixed.
![schermata-09-21-13-57](https://user-images.githubusercontent.com/10681413/134166728-c4fe2164-c53f-465d-a35f-7a7259eeea16.png)

##### Expected Behavior

All actions displayed in context menus are working
##### Current Behavior

select all  and invert selection isn't, also custom actions.
##### Possible Solution

Make it work (for deletion or copying), or grey it out,
##### Steps to Reproduce (for bugs)

1. RIght click on empty space in thumbnail preview
2. Click "select all", the first or the second item get selected, same for cltr+a, repeating it it switches among them,
3. click  invert selection, switching again between first and second item

                                                    --->
* LXimage-qt version: git master
:

**Comment by tsujan** [comment]
> select all and invert selection isn't

They shouldn't because the view is made in such a way that only one item can be selected.

> also custom actions

Custom actions that support a single file/folder work fine here.

**Comment by tsujan** [comment]
> thinking about only greying out is ok.

I agree and self-assign.

**Comment by tsujan** [comment]
The PR is https://github.com/lxqt/libfm-qt/pull/733. It isn't limited to this special case; your report was valid outside lximage-qt too.
