### ISSUE TITLE
Horizontal flipping is broken

### ISSUE THREAD

**Issue by Dialga** [lxqt/lximage-qt#470]
##### Expected Behavior

Press H to horizontally flip image.
##### Current Behavior

Pressing H to horizontally flip image flips the image horizontally then vertically.
##### Possible Solution

Press H to horizontally flip image only.
##### Steps to Reproduce (for bugs)

1. Open jpg image
2. Press H
3. Image is flipped horizontally
4. Image is flipped vertically

##### System Information

* LXimage-qt version: 0.17.0
* Distribution & Version: Arch Linux
* Qt Version: 5
* liblxqt Version: 0.17.0

**Comment by Dialga** [comment]
Not sure if this is related, but there is a duplicate line here:

https://github.com/lxqt/lximage-qt/blob/b771fe7efe633419f10a749166a625cb4e5b773c/src/mainwindow.cpp#L205-L206

**Comment by tsujan** [comment]
Thanks for the report! I'll fix the problem soon.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/lximage-qt/pull/471

It was a single typo that, by chance, had effect only when the image was made smaller than its original size and also when it wasn't SVG or GIF. That was why the bug had remained hidden.

The redundant line that you mentioned was a harmless typo; I removed it in the same PR.

**Comment by tsujan** [comment]
BTW, thanks to this report, I found another bug in flipping (whether vertical or horizontal), for which I'll open an issue and add a fix later.

**Comment by Dialga** [comment]
Glad I can be of help!

> BTW, thanks to this report, I found another bug in flipping (whether vertical or horizontal), for which I'll open an issue and add a fix later.

**Comment by tsujan** [comment]
> Glad I can be of help!

A great help, indeed! The issue I've found is nasty and, if you didn't make this report, it might go into the next version (in November).
