### ISSUE TITLE
"Nasty" problems in image flipping and rotating

### ISSUE THREAD

**Issue by tsujan** [lxqt/lximage-qt#472]
##### Steps to Reproduce (for bugs)

1. Open a PNG image whose width and height are very different from each other, so that there's enough space for it and also for its rotated forms when you make the window of lximage-qt large enough.
2. Make the window large enough so that the image won't need to be resized if rotated.
3. First, flip it vertically.
4. Then rotate it clockwise or counterclockwise.

Then, you'll see that the rotated image is misplaced.

After that:

 1. Close all windows of lximage-qt.
 2. Put 2 big enough PNG images with the same size inside another empty folder, so that if you fit them, they'll be made smaller.
 3. Open the first image and fit it inside the view.
 4. First, flip it vertically.
 5. Then, go to the next image, and then go back to the previous image, and...

You'll see the problem.

Other combinations of these problems are also possible.

##### Possible Solution

Contrary too their appearances, all these issues can be fixed easily. I'll make a PR soon.

##### Context

I wouldn't notice these problem if it weren't for @Dialga's [report](https://github.com/lxqt/lximage-qt/issues/470).

##### System Information

* Latest git

**Comment by tsujan** [comment]
@stefonarch, could you confirm the above-mentioned issues? It's so strange to me why they weren't detected before. Am I the only one who sees them by some mistake?

**Comment by stefonarch** [comment]
I tried the  one with the flipping and couldn't reproduce it in a first moment, I misunderstood the size thing. 
I can reproduce it well if the image is bigger than the window size, and it looks like at first run it's different - I can see first a flip horizontally and immediately after vertically, after that it directly flips other files  vertically.

Will try out those here now.

**Comment by tsujan** [comment]
Good.

Applied the fixes here and the erratic behavior is gone. Will make a PR after more tests.

**Comment by stefonarch** [comment]
With the first steps it goes out of sight, with the second it flips also vertically if fit to window is set.

**Comment by tsujan** [comment]
Exactly what I see here :)

**Comment by tsujan** [comment]
Saving of images also had a problem (the saved image wasn't loaded when an existing image was saved to another place). Because it was somehow related to transformations, I fixed it in [the same PR](https://github.com/lxqt/lximage-qt/pull/474).
