### ISSUE TITLE
[Feature request] Show version number in about window

### ISSUE THREAD

**Issue by Dialga** [lxqt/lximage-qt#473]
**Is your feature request related to a problem? Please describe.**

Currently clicking on the about dialog, there is no version number of lximage.

**Describe the solution you'd like**

The about window includes the version number of lximage.
The about dialog in applications normally show the version number of the application that's running, that way an end user can quickly report about buggy versions.

**Describe eventual alternatives you've considered**

#### Context

Arch Linux

**Comment by stefonarch** [comment]
True, pcmanfm-qt and screengrab report their versions.

**Comment by Dialga** [comment]
> But actually the copyright should also be updated.

Yes I was also going to mention that.

**Comment by tsujan** [comment]
In addition, why limiting it to plain-text? Will make it like this after https://github.com/lxqt/lximage-qt/pull/474 is merged:

![about](https://user-images.githubusercontent.com/981076/135035646-e6cd47a2-0454-4798-a739-3b44962b7683.png)

It removes unnecessary characters and strings from translation, so that it won't be broken by updating the version and copyright.

**Comment by stefonarch** [comment]
Nice!

**Comment by stefonarch** [comment]
Btw, version number, will we stick to 0.1x  still?

**Comment by tsujan** [comment]
> Btw, version number, will we stick to 0.1x still?

I don't know. Next month, we could ask other members. What's your opinion?

**Comment by stefonarch** [comment]
> I don't know. Next month, we could ask other members. What's your opinion?

I'm fine with everything, but going over 0 would be nice at the point we are. 
I saw today a typo [here](https://emmabuntus.org/on-september-20th-2021-emmade4-under-debian-11-bullseye-stable-version/), LXQt 8.16.0 way far in the future but very nice version number  ;)

**Comment by tsujan** [comment]
> I'm fine with everything, but going over 0 would be nice at the point we are. 1.17?

If we want to bump the first number, it'll be 1.0.0.

> Btw a very well done and complete distribution

Wherever I see an old version of LXQt, all the bugs that were fixed after it come to my mind ;) Also 0.17 will be old soon.

**Comment by stefonarch** [comment]
> Wherever I see an old version of LXQt, all the bugs that were fixed after it come to my mind ;) Also 0.17 will be old soon.

That's natural for who is in, but I'd say from 0.16 most things where quite ok, no need to talk too bad about ;)
