### ISSUE TITLE
[Feature request] Have full list of installed icon themes in Settings

### ISSUE THREAD

**Issue by EugeneUvin** [lxqt/lximage-qt#476]
**Is your feature request related to a problem? Please describe.**
I've installed lximage-qt to KDE Plasma to replace Gvenview (which has features I never use). The problem is: I use ePapirus-Nordic icon theme, and it is not in the list of icon themes available in the app's settings.
![изображение](https://user-images.githubusercontent.com/9447963/134912952-56097f05-e244-4d0b-8dd6-39dba4922271.png)

**Describe the solution you'd like**
It would be great if the app could show the list of all installed icon themes, and not just some default list hard coded into UI. Or, if this is not acceptable, add popular ePapirus icon themes into the hard coded list.

**Describe eventual alternatives you've considered**
I tried to install LXQt theme manager (while still using KDE), but it did not change app's icon settings.

Current solution I've applied: Icon theme can be set by manually editing ~/.config/lximage-qt/settings.conf, and it just works, though the theme does not appear in the UI list:

`fallbackIconTheme=ePapirus-Nordic`

```
[General]
bgColor=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
fallbackIconTheme=ePapirus-Nordic
fullScreenBgColor=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
recentlyOpenedFiles=/home/...
slideShowInterval=5

[Window]
FixedHeight=480
FixedWidth=640
LastWindowHeight=952
LastWindowMaximized=false
LastWindowWidth=910
RememberWindowSize=true

```

#### Context
Some LXQt apps are good to use in KDE Plasma desktop. It would be great if those apps keep icon theme consistent with KDE Plasma apps.

**Comment by stefonarch** [comment]
Which version of LXimage-qt do you have? I don't remember any setting for icon themes.
`lximage-qt -v`

**Comment by tsujan** [comment]
> I don't remember any setting for icon themes.

I think, like in pcmanfm-qt, it appears only outside LXQt. Will check it later.

**Comment by EugeneUvin** [comment]
> Which version of LXimage-qt do you have? I don't remember any setting for icon themes.
> `lximage-qt -v`

lximage-qt 0.14.1

I thought if I install LXQt theme setup, it will control LXQt apps though the rest of the system is KDE, but it looks like each app has separate settings for icon theme in that case. Would be great if LXQt apps recognize KDE theme and apply it in that case - could that work?

The setting is in Edit -> Settings (I'm guessing English names, the interface is in Russian on my PC).

**Comment by tsujan** [comment]
> but it looks like each app has separate settings for icon theme

That option is only for DEs that lack a Qt plugin and for user convenience. LXQt and KDE has their own Qt plugins/icon loaders. By default, all Qt apps should use KDE's active icon set under KDE.

**Comment by tsujan** [comment]
OK, I checked the code and also tested by removing `XDG_CURRENT_DESKTOP` and `QT_QPA_PLATFORMTHEME`. That option showed up and listed all installed icon sets. Moreover, the option didn't appear under KDE, as it shouldn't.

I'm afraid your installed version is too old (the latest is 0.17).

**Comment by tsujan** [comment]
> I'm using Kubuntu 20.04

Oh, all its apps should be very old.

We appreciate bug reports and fix issues as soon as possible. But please use the issue template when reporting!

**Comment by EugeneUvin** [comment]
Got it, I am new to reporting - will enter all details next time. Thank you for the wonderful product!

**Comment by stefonarch** [comment]
I'm late, and I learned about that only now, testing an openbox session in Lubuntu 21.10 which ships LXQt 0.17
As you can see all icons installed are listed:
![schermata-09-27-20-03](https://user-images.githubusercontent.com/10681413/134961535-9cbca109-8d4c-438b-8d13-e2eb282af194.png)

**Comment by EugeneUvin** [comment]
@stefonarch this works in 20.04 as well, I mean this settings app.

Next time I'll ensure I put all details into the ticket to not waste your time. Thank you for proactively looking into this.
