### ISSUE TITLE
I cannot 'make'.

### ISSUE THREAD

**Issue by romanwarlock** [lxqt/lximage-qt#518]
Please, write a more detailed instruction of 
i)what other packages should be installed
ii) how to 'make',
iii) and where to put the executable file
with instructions written so far in readme.md
make
**me@pc:/.../lximage-qt-1.0.0**$ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by tsujan** [comment]
I'm afraid basic concepts of compilation should be learned before compiling. It's not a program's job to explain them.

**Comment by stefonarch** [comment]
Detailed instructions about building and build order (requisites) you can find in https://github.com/lxqt/lxqt/wiki/Building-from-source#compiling-all-components-individually
