### ISSUE TITLE
Esc-key has strange behavior in two cases

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lximage-qt#529]
case 1
- open the viewer
- press Esc

##### Current Behavior
viewer is closed

##### Expected Behavior
only Ctrl+W should close the viewer (so it is described in in the menu-bar in File and in the Preferences in Shortcuts)

<br><br><br>
case 2
- open the viewer
- press F11
- press Esc

##### Current Behavior
sometimes there is no full-screen any more, but in the most cases nothing happens;
if full-screen is still there, I have to press again Esc, so in sum 2x to leave full-screen

##### Expected Behavior
viewer should leave full-screen with 1x Esc

##### System Information
LXQt 0.17.0
Lubuntu 21.10
I don't know how to find the version of my lximage-qt.

**Comment by tsujan** [comment]
> case 1

Intentional.

> case 2

0.17.0 is outdated. The bug was fixed before 1.0.0.

**Comment by ralf3u** [comment]
And I just recognized a third case:

open viewer
if viewer is not maximized: maximize the window
press F11 to go in full-screen
press F11 to leave full-screen
press Esc to close the viewer
open the viewer again

result
viewer is not maximized any more

**Comment by tsujan** [comment]
> And I just recognized a third case:

Leaving the fullscreen mode doesn't require restoring the maximized mode if the window was maximized before getting fullscreen but, yes, it's better to do that. → https://github.com/lxqt/lximage-qt/pull/530
