### ISSUE TITLE
erase in the menu "View" the checkbox next to "Full Screen"

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lximage-qt#531]
Steps to reproduce
in the menu "View": activate the checkbox next to "Full Screen"
press F11 to leave full-screen

Result
in the menu "View": now the checkbox next to "Full Screen" is activated although lximage-qt is not in full-screen

Possible solution
a
I would delete the checkbox because it creates confusion.
Even if the checkbox would be deactivated, I don't see a sense for a checkbox because there is no need to verify if it is activated or deactivated. If the program is in full-screen, then there is no menu. Then how could I verify it in full-screen?
b
And next to the suggestion to erase the checkbox, maybe this could be also interesting:
change in "View" `Full Screen` to `Full Screen on/off`.
c
if a and b are not welcomed, then the alternative is to correct the checkbox in that way that it is deactivated (see above in Result)

System
Lubuntu 21.10
my lximage-qt (LXQt 0.17.0) is old, but I still don't know how to install the new version;
if the issue does not appear in 1.0.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
It was fixed before 1.0.0 was released.
