### ISSUE TITLE
dark system-theme is not respected

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lximage-qt#532]
steps to reproduce
in the file-manager: open a dark image

result
I can see white color around the image, although I use a dark theme in Lubuntu

Expectation
lximage-qt should respect the dark system-theme

Comparison
PcManFM-Qt respects the dark system-theme

System
Lubuntu 21.10
my lximage-qt (LXQt 0.17.0) is old, but I still don't know how to install the new version;
if the issue does not appear in 1.0.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
lximage-qt doesn't have a style of its own. Only its view has a configurable background, as it should.
