### ISSUE TITLE
Use of the spacebar  key to pause/resume a slideshow

### ISSUE THREAD

**Issue by Thorny-Twig** [lxqt/lximage-qt#540]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To be able to use the **_spacebar_** key on a keyboard to pause and resume playing of a **Slide show** of images, in particular when showing the **Slide show** in **Full Screen** mode.

**Describe eventual alternatives you've considered**
Tried all the keys on the keyboard but none preform the required task.

#### Context
I would just like to have the ability be able to pause a Slide show on any image of importance during a presentation.

**Comment by tsujan** [comment]
Assign `Space` to Preferences → Shortcuts → Slide Show.

**Comment by Thorny-Twig** [comment]
Great thanks for help. When I set up the Slide Show to use `Space` as a shortcut, it doesn't work for me on machine but using a different key like `s` it work perfect. Using Ubuntu 21.10 and version 0.17 of lximage-qt

**Comment by tsujan** [comment]
The problem you described doesn't exist in the latest release (1.0.0).
