### ISSUE TITLE
Add Finnish language to Weblate [Feature request]

### ISSUE THREAD

**Issue by heidiwenger** [lxqt/lximage-qt#567]
People notified me that they would have liked to help on LXimage-qt translations but the "start a new translation" button is unclickable or greyed out for some reason.

**Comment by Chiitoo** [comment]
It requires some extra permissions I believe, which I happen to possess, and as such, I have just clicked the button and it should be good to go.

**Comment by stefonarch** [comment]
Unfortunately many people don't find the [instructions](https://translate.lxqt-project.org/projects/lxqt-desktop/#information). Indeed if some files are not present translators need to ask for upgrade of permissions which will be given. 
But without knowing the username I cannot proceed :)
I'll merge the file created by chitoo now.
