### ISSUE TITLE
[Feature request] `Open with` does not auto-save or suggest to save

### ISSUE THREAD

**Issue by opk12** [lxqt/lximage-qt#573]
**Is your feature request related to a problem? Please describe.**
When working on a screenshot made with `lximage-qt-screenshot`, `File` - `Open with` is greyed out (disabled) and there is no indication of the reason.

**Describe the solution you'd like**
`Open with` automatically saves to temporary file, or opens the `Save as` prompt, or shows a message that explains why it is disabled.

**Describe eventual alternatives you've considered**

#### Context
I want to screenshot, then crop, blur, write labels, draw circles. Digging the GitHub issues, I found manual saving is required. This should be advertised or done automatically, because it's not the user workflow, manual saving is a workaround for not auto-saving.

lximage-qt v 0.16.0-1 from Debian 11 repo

**Comment by stefonarch** [comment]
The screenshot tool of LXQt is screengrab, which offers all you like to have, the screenshot part isn't developed furthermore.
The .desktop file for screenshots has even  been removed from LXimage-qt back  in LXQt 1.0.0.
