### ISSUE TITLE
Support changing implicit sort order

### ISSUE THREAD

**Issue by eyalroz** [lxqt/lximage-qt#574]
lximage-qt supports moving between image files in a directory - forwards or backwards. But - what are the "next" or "previous" files for a given file? There is an implicit sort order lximage-qt adheres to.

I suggest that this sort order be made explicitly configurable - like in a file browser: That users be able to choose the sort field (name, extension-then-name, ctime-then-name, mtime-then-name, size-then-name) and the sort order (ascending/descending).

Personal motivation: I sometimes get images whose names are not in any particular order, but their modify-times are. I would rather than have to rename them all in order to view them in order.

**Comment by tsujan** [comment]
Until it's implemented — provided that it proves to be a popular enough feature — you could use the thumbnail view and sort it by right clicking an empty space inside it. Of course, the sorting won't be remembered (the feature means that it should be remembered consistently).

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/lximage-qt/pull/575
