### ISSUE TITLE
Window size is not remembered when pressing F11 one or two times

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lximage-qt#587]
choose an image in the file-manager
press enter
maximize the window
press F11 to go in full-screen or press F11 two times
close the window
choose the same image in the file-manager
press enter
the window is not maximized

remarks
- issue appears also when going in LXImage-Qt in full screen with a double click on an image, and then closing the window
- issue does not appear when going in LXImage-Qt in full screen with a double click on an image, and then double click on an image again to leave full screen, and then closing the window

Lubuntu 22.10
lximage-qt 1.1.0

**Comment by tsujan** [comment]
Correct me if I'm wrong; you're saying is that if the window is maximized, made full-screen, and then closed, the next time it won't be maximized. Well, that isn't reproducible here.

**Comment by tsujan** [comment]
BTW, what you see may be related to WM. I tested with KWin and Wayfire (a Wayland WM/compositor); the window was maximized. If you use Openbox, it may be the culprit.

**Comment by ralf3u** [comment]
>Yes, it's an Openbox bug.

I just filled a report at https://bugzilla.icculus.org/show_bug.cgi?id=6653.

**Comment by tsujan** [comment]
> I just filled a report at https://bugzilla.icculus.org/show_bug.cgi?id=6653.

Openbox's development stopped years ago, which means that its bugs will never be fixed. It's still usable but if you use it, you'll have to tolerate its bugs.

**Comment by ralf3u** [comment]
On the reported bug, there is now a comment:

https://bugzilla.icculus.org/show_bug.cgi?id=6653#c1

The comment seems to point the issue on the application.

**Comment by tsujan** [comment]
> The comment seems to point the issue on the application.

What he's saying is just that he doesn't know that the app does its job: it announces that the window should be maximized, but Openbox doesn't show it maximized.
