### ISSUE TITLE
PCX not supported by QImageReader, should not be listed in .desktop file

### ISSUE THREAD

**Issue by fenugrec** [lxqt/lximage-qt#592]
https://github.com/lxqt/lximage-qt/blob/3bc6161c23b490737d340943e98bdbcd108ed2e4/data/lximage-qt.desktop.in#L8

`application/pcx` and `image/x-pcx` should be removed from `data/lximage-qt.desktop.in`, unless I'm misunderstanding something or missing a non-obvious optional dependency ?

At least, PCX is not listed in the qt6 docs for  qimagereader :
https://doc.qt.io/qt-6/qimagereader.html#formats

For reference, the attached image cannot be opened, as expected.
[S5.PCX.zip](https://github.com/lxqt/lximage-qt/files/10363329/S5.PCX.zip)

**Comment by tsujan** [comment]
"pcx" is among the formats supported by Qt5, on which lximage-qt is based currently.

But you're right: (1) Qt5 can't handle it (correctly), and (2) Qt6 doesn't support it. It will be removed when lximage-qt is ported to Qt6.

**Comment by tsujan** [comment]
BTW, a funny comparison:

Qt5 supports "3fr", "ani", "arq", "arw", "avif", "avifs", "bay", "bmp", "bmq", "bw", "cap", "cine", "cr2", "cr3", "crw", "cs1", "cur", "dc2", "dcr", "dcs", "dng", "drf", "dxo", "eip", "eps", "epsf", "epsi", "erf", "exr", "fff", "gif", "hdr", "heic", "heif", "icns", "ico", "iiq", "jp2", "jpeg", "jpg", "jxl", "k25", "kc2", "kdc", "kra", "mdc", "mef", "mfw", "mng", "mos", "mrw", "nef", "nrw", "obm", "ora", "orf", "ori", "pbm", "pcx", "pdd", "pdf", "pef", "pgm", "pic", "png", "ppm", "psb", "psd", "psdt", "ptx", "pxn", "qtk", "r3d", "raf", "ras", "raw", "rdc", "rgb", "rgba", "rw2", "rwl", "rwz", "sgi", "sr2", "srf", "srw", "sti", "svg", "svgz", "tga", "tif", "tiff", "wbmp", "webp", "x3f", "xbm", "xcf", "xpm".

While, here, Qt6 supports "bmp", "cur", "gif", "icns", "ico", "jp2", "jpeg", "jpg", "mng", "pbm", "pdf", "pgm", "png", "ppm", "svg", "svgz", "tga", "tif", "tiff", "wbmp", "webp", "xbm", "xpm".

**Comment by fenugrec** [comment]
> "pcx" is among the formats supported by Qt5

Ok, where is that documented ? A quick look at https://doc.qt.io/qt-5/qimagereader.html#supportedImageFormats doesn't show it...

I think `::supportedImageFormats()` doesn't return PCX, at least on my system, because File->Open dialog doesn't even list PCX.

**Comment by tsujan** [comment]
> Ok, where is that documented ?

Qt didn't give a list in its doc the last time I checked. Just see `QImageReader::supportedImageFormats()`.

Anyway, PCX (and many other formats) will be removed soon.

**Comment by fenugrec** [comment]
> Yes, I have it here. If it's a Qt plugin,

So that would be the explanation : https://api.kde.org/frameworks/kimageformats/html/index.html

**Comment by tsujan** [comment]
> So that would be the explanation : https://api.kde.org/frameworks/kimageformats/html/index.html

You're right. Thanks for finding it!

I'm under LXQt+Wayfire now. Your attached PCX image is shown as a completely transparent rectangle by both lxmage-qt and another Qt-based viewer of mine. Will test it under X11 later.

**Comment by fenugrec** [comment]
I would still suggest adding a note about kimagereader as an optional dependency somewhere in the README ?

**Comment by tsujan** [comment]
Let's reopen this. My question is more general: Shouldn't we include only those formats in the desktop file that Qt supports without any plugin?

**Comment by fenugrec** [comment]
>  Shouldn't we include only those formats in the desktop file that Qt supports without any plugin?

You will have guessed that my quick answer would be "yes", because it's a safe default, and I'm not sure if it's realistic to 
 - modify .desktop file at the distro end to add extra entries depending on installed plugins
 - modify .desktop.in file here with some equivalent cmake magic to detect a few common plugins , or to call  `supportedImageFormats`  ? seems like a lot of complexity

**Comment by fenugrec** [comment]
> And I agree with you. But some users might kill us ;)

Any non-trivial always has a risk of upsetting a certain group of users, that's true. I'm not well placed to judge.

> What about keeping the current formats and adding a note about `kimageformats`?

That would be an improvement, yes.

**Comment by tsujan** [comment]
OK, will add a note to README.

BTW, I logged into LXQt+kwin_x11 and opened the image. This time, it's a black rectangle. Why it's transparent under Wayland and black under X11+compositing, I don't know.

KDE's gwenview has exactly the same behavior. I added the info to your report (https://bugs.kde.org/show_bug.cgi?id=463951).

**Comment by stefonarch** [comment]
Just tried to open the image here: it opens fine with PhotoQt imageviewer (appimage) which apparently is the default for this type on my installation.

**Comment by tsujan** [comment]
It can be opened by GIMP too. The problem was that `kimageformats` should enable all Qt image viewers to open it, but it didn't.

**Comment by tsujan** [comment]
Oh, we forgot about `qt5-imageformats`. Added it to https://github.com/lxqt/lximage-qt/pull/593 too.
