### ISSUE TITLE
[Feature request] Switch to toggle antialiasing filter

### ISSUE THREAD

**Issue by kzhang2** [lxqt/lximage-qt#598]
**Is your feature request related to a problem? Please describe.**

When I'm viewing images with a small resolution, the antialiasing that the image viewer does makes the image very blurry.

**Describe the solution you'd like**

I would like for there to be an option to turn off the antialiasing filter. 

**Describe eventual alternatives you've considered**

#### Context

I do research in computer vision where I have to view small resolution images all the time that I expect to be somewhat "blocky". The antialiasing filter makes it harder for me to visualize the results of my work. 

Honestly, I might be able to implement this myself. Let me know if you guys think that's a good idea.

**Comment by tsujan** [comment]
Already implemented. Unckeck `Preferences → Image → Smooth images on zooming`.
