### ISSUE TITLE
[Feature request] Add line wrap support to SVG

### ISSUE THREAD

**Issue by Artem13327** [lxqt/lximage-qt#607]
Without wrapping, some SVGs look strange.

**Comment by tsujan** [comment]
What do you mean by "wrapping"?

**Comment by tsujan** [comment]
If by "line wrapping" you mean wrapping the lines of the XML text of an SVG image, it has nothing to do with lximage-qt.

lximage-qt doesn't manipulate SVG images but shows them by using what Qt provides.
