### ISSUE TITLE
Small app icon

### ISSUE THREAD

**Issue by tsujan** [lxqt/lximage-qt#609]
The app icon is a blurry 48-pix PNG image.

I propose this SVG image, that I made based on the current icon (it's only 3 KB):

![lximage-qt](https://user-images.githubusercontent.com/981076/230743817-b4450fb7-fe1a-42f7-86af-456ddc889f53.png)

**Comment by stefonarch** [comment]
GTM

**Comment by tsujan** [comment]
What about this variant? Which looks better?

![lximage-qt](https://user-images.githubusercontent.com/981076/230757638-34334f49-eb15-4d56-82b3-094f0fadafd9.png)

**Comment by tsujan** [comment]
And this one:

![lximage-qt1](https://user-images.githubusercontent.com/981076/230758065-9c0cd0d2-a5fe-4852-b166-507daf3adb41.png)

**Comment by stefonarch** [comment]
the first one, IMO

**Comment by tsujan** [comment]
The third icon seems more elegant to me (I used the second one in my icon set).

**Comment by stefonarch** [comment]
To be honest it looks like this  "can you spot the differences? " questions ;)

**Comment by tsujan** [comment]
I used a refined version of the third icon in https://github.com/lxqt/lximage-qt/pull/610.

> To be honest it looks like those "Can you spot the differences? " questions ;)

I know what you mean. These matters are mostly subjective, and tastes differ. In general, an icon should look good enough against both light and dark backgrounds.
