### ISSUE TITLE
[Feature request] Option to disable partial rendering

### ISSUE THREAD

**Issue by Marco-Sulla** [lxqt/lximage-qt#613]
**Is your feature request related to a problem? Please describe.**

I noticed that when I switch from an image to another, the next image is first partially rendered.
These are probably progressive jpg.

**Describe the solution you'd like**
I'd like an option that will show the image only when is completely rendered.

**Describe eventual alternatives you've considered**
I don't know. Other programs? X-D

**Comment by tsujan** [comment]
Please be more specific. What do you mean by "partial rendering"? Which version of lximage-qt?

**Comment by Marco-Sulla** [comment]
I mean that lximage-qt do something like this:
https://www.hostinger.com/tutorials/wp-content/uploads/sites/2/2016/11/progressive-jpeg-load.webp

**Comment by tsujan** [comment]
Could you attach that image?

**Comment by tsujan** [comment]
Oh, never mind! You mean smoothing on zooming. There's already an option for disabling it: Preference  → Image → Smooth images on zooming. If you don't see that option, your installed lximage-qt is outdated.
