### ISSUE TITLE
Opening an image opens another image in the folder instead of the double clicked image

### ISSUE THREAD

**Issue by glu8716** [lxqt/lximage-qt#632]
##### Expected Behavior

- Double click image "a"
- Image "a" opens

##### Current Behavior

- Double click image "a"
- Image "b" opens

##### Steps to Reproduce (for bugs)

1. Open an image while having other images in a folder
2. See if the correct image opens

##### Context

I have no particular information to add as this seems to happen randomly in no particular context.
EDIT: I recorded a clip to show the behavior.
[simplescreenrecorder-2023-08-04_13.42.44.webm](https://github.com/lxqt/lximage-qt/assets/33501455/282275bf-5c5a-472e-974f-bd312a78392d)

##### System Information

* LXimage-qt version: 1.3.0
* Distribution & Version: Artix Linux
* Qt Version: 5.15.10
* liblxqt Version: 1.3.0-1

**Comment by tsujan** [comment]
Not reproducible.

If you find the necessary condition(s) for reproducing it, please add a comment.

**Comment by glu8716** [comment]
@tsujan I think this is happening when the images are stored in another drive which is not the one where the system and the program are installed. Also, it seem to happen only if the images are stored in a subfolder. 

For example I have the folder `test` with four images: `a.jpg` `b.jpg` `c.jpg` `d.jpg`. I made some tests.

Images open correctly if they are in the path:
`/home/myusername/Pictures/test`

Images open correctly if they are in the path:
`/mnt/myhdd1`

`d.jpg` opens instead of `a.jpg `if the pictures are in the path:
`/mnt/myhd1/test`

Images open correctly if they are in the path:
`/mnt/myhdd2`

`a.jpg` opens instead of `d.jpg `if the pictures are in the path:
`/mnt/myhdd2/test`

**Comment by tsujan** [comment]
As it was said previously, it isn't reproducible in the way you describe it. Such an issue couldn't be missed if it existed for all. There should be an additional, hidden info in your case.

lximage-qt 1.3.0 is outdated now. The latest version is 2.1.0.

**Comment by glu8716** [comment]
Unfortunately I'm not able to identify any other pattern that is causing this. Do you have any idea on what I could look into?

**Comment by tsujan** [comment]
>  Do you have any idea on what I could look into?

Does it happen with all image formats? Is the number of images a factor? Or their file sizes? Does it happen without the thumbnail view? What about a new user? And so on…

**Comment by glu8716** [comment]
The number of images is not a factor. I have multiple folders with multiple images and this problem occurs in both.
As for the format, I'm sure I had it happening with both jpg and png.
It happens with/without the thumbnail view. In fact, it happens also if I open the images from the terminal, eg: `lximage-qt a.jpg` will open `d.jpg` instead.
I don't think this is a user-related problem because I've recently reinstalled my system so I'm now using a completely different user.

I also found out that this is not consistent. After rebooting the computer, today only if I open `b.jpg`, `d.jpg` is opened instead. `a.jpg` and `c.jpg` open fine.

I'll keep investigating...

**Comment by tsujan** [comment]
> I'll keep investigating...

Good. Also, I'll check the code again — although I checked it 3 times after your comment and saw nothing suspicious.

**Comment by tsujan** [comment]
OK, I checked the code again and found nothing that could cause what you see.

Indeed, what you see is the strangest thing I've encountered recently ;) I don't have the slightest idea what could have caused it, but it's very unlikely that its cause can be in lximage-qt. There's no random factor in lximage-qt about showing an image, and specially, the path isn't important.
