### ISSUE TITLE
Confusing and contradictory licensing information

### ISSUE THREAD

**Issue by ArrayBolt3** [lxqt/lximage-qt#645]
##### Expected Behavior
Licensing info in lximage-qt's source code should be consistent and easy to understand.

##### Current Behavior
Licensing info is confusing and in some places contradictory.

##### Steps to Reproduce (for bugs)
1. View the `AUTHORS` file. The license is specified as "GPL-2+ and LGPL-2.1+". From the perspective of a copyright auditor, this means that a user must comply with the terms of both the GPLv2 (or any later version) and the LGPLv2.1 (or any later version). This was probably intended to be a summary, not a combination of licenses, but it has the effect of combining the licenses.
2. View `data/lximage-qt.metainfo.xml`. The `<project_license>` tag specifies `GPL-2.0-only`. This doesn't match with the earlier declaration of GPL-2+.
3. `cd` into the `src` directory and run `grep -r -i "LGPL"` and `grep -r -i "Lesser"`. There doesn't appear to be any occurrence of the LGPL license anywhere in the lximage-qt codebase.

##### Suggested fix
1. Change the `<project_license>` tag in `data/lximage-qt.metainfo.xml` to `GPL-2.0-or-later`.
2. Change `AUTHORS` to specify `GPL-2+` as the repo-wide license and add an explicit LGPL-2.1+ license header to files that are intended to be usable under that license.

**Comment by tsimonq2** [comment]
Ubuntu and Debian are particularly strict about consistent licensing. If we find anything else in the LXQt source code, we'll be sure to let you know. Otherwise, we'd appreciate a simple and smooth remedy for this.

Thank you very much for your time!
