### ISSUE TITLE
[Feature request] Support heif format

### ISSUE THREAD

**Issue by Marco-Sulla** [lxqt/lximage-qt#647]
I just discovered HEIF with my new cellphone. I just noticed that the size of image are much more smaller than JPEG.

There's a literature on internet about HEIF and the advantages over JPEG. I think it's a format that deserve to be supported.

For what I read in another post, HEIF is no more supported by Qt6:
https://github.com/lxqt/lximage-qt/issues/592#issuecomment-1374196732

Is there not a way to add HEIF to a Qt 6 app? Google seems to suggest a few options:
https://www.google.com/search?channel=fs&client=ubuntu-sn&q=HEIF+qt6

**Comment by tsujan** [comment]
Extra image formats are provided by Qt plugins like `qt5-imageformats` and `kimageformats`, not by lximage-qt. If they're installed and support a format, lximage-qt will show it, and you could use LXQt File Associations (or a similar tool) to assign that format to lximage-qt.

**Comment by isf63** [comment]
Installing `kimageformats` and `libheif` will provide HEIF support.

`/usr/lib/qt/plugins/imageformats/kimg_heif.so` is provided by kimageformats but needs libheif to work.

On Arch at least, qt5-imageformats is listed as an optional dep to lximage-qt, but kimageformats is not.

**Comment by tsujan** [comment]
> On Arch at least,...

We've mentioned `kimageformats` in [README](https://github.com/lxqt/lximage-qt).

**Comment by Marco-Sulla** [comment]
I installed `kimageformat-plugins` but still no HEIF support. `libheif1` and `qt5-image-formats-plugins` are already installed. I have also rebooted the pc to be sure.

PS: why `kimageformat-plugins` is not installed by default?

**Comment by Marco-Sulla** [comment]
It seems HEIF on `kimageformat-plugins` is not enabled by default:

https://askubuntu.com/a/1375987/156176

I'll try and let you know.

**Comment by tsujan** [comment]
> why kimageformat-plugins is not installed by default?

It depends on your distro (whether it marks `kimageformats` as a "recommended", "optional",… package for `lximage-qt`) , and how you use your distro's  package manager (whether you also install recommended/optional/… packages).

**Comment by Marco-Sulla** [comment]
I use Lubuntu.

The above steps worked for me.

There's a open bug on Launchpad about this: https://bugs.launchpad.net/ubuntu/+source/kimageformats/+bug/1951278

**Comment by tsujan** [comment]
> I use Lubuntu.

Then you might also want to check if the deb package of `kimageformats` is in the "Recommends" list of the deb package of `lximage-qt` and, if it isn't, report that to Lubuntu.

**Comment by Marco-Sulla** [comment]
> report that to Lubuntu

Reported here:
https://bugs.launchpad.net/ubuntu/+source/kimageformats/+bug/2044619

**Comment by tsujan** [comment]
Good. Other Ubuntu users may also benefit from it.

In the meanwhile, I checked https://packages.ubuntu.com/noble/lximage-qt; `kimageformats` wasn't under the "recommends" category. It is under the "optional" category in Arch: https://archlinux.org/packages/extra/x86_64/lximage-qt/
