### ISSUE TITLE
Checkbox for annotations toolbar resets always to non checked

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lximage-qt#654]
##### Expected Behavior

Checked View > Annotations Toolbar i persistent
##### Current Behavior

It is not.

##### Steps to Reproduce (for bugs)

1. Check the mentioned checkbox
2. toolbar is shown
3. close and reopen the app
4. no annotations toolbar is shown

##### System Information

* LXimage-qt version: 1.4, git
* Distribution & Version: arch, debian

**Comment by stefonarch** [comment]
By default in `~/.config/lximage-qt/settings.conf` the value for
`ShowAnnotationsToolbar` is "false" and if changed to "true" the toolbar is shown always.
It just never writes to the config file changes.

**Comment by tsujan** [comment]
Will check it later -- but only for the Qt6 branch.

**Comment by tsujan** [comment]
Oh, no check is needed; everything is OK.

That check-box isn't for the next session. If you want to show annotations in all session, check Preferences → Window → Show annotation toolbar by default.

**Comment by stefonarch** [comment]
Shame on me, I just saw the other 2 always checked....

**Comment by tsujan** [comment]
It happens....

The user may want to show thumbnails bar or annotations toolbar to do something, but he may prefer them to remain hidden by default -- or conversely. Hence, the permanents settings are only in Preferences.
