### ISSUE TITLE
Wrong mimetype for PGM (image/x-portable-graymap) files

### ISSUE THREAD

**Issue by joshuakraemer** [lxqt/lximage-qt#673]
##### Expected Behavior
PGM (image/x-portable-graymap) files should be opened with LXImage-Qt.

##### Current Behavior
In LXImage-Qt's desktop file, the PGM mimetype is misspelled as "image/x-portable-gr**e**ymap". Therefore, LXImage-Qt is not registered for PGM files in the application database.

##### Possible Solution
I think the spelling in the desktop file should be changed to "image/x-portable-graymap". This is the spelling suggested in the documentation at https://netpbm.sourceforge.net/doc/pgm.html, the spelling used in "/usr/share/mime/packages/freedesktop.org.xml" and also the spelling returned by `gio info file.pgm`. As a workaround, LXImage-Qt can be manually registered for PGM files with the command `xdg-mime default lximage-qt.desktop image/x-portable-graymap`.

##### Steps to Reproduce (for bugs)
1. Download PGM sample file from https://sembiance.com/fileFormatSamples/image/pgm/lennasmall.pgm
2. Locate the file in PCManFM-Qt and try to open it with LXImage-Qt

##### Context
Not relevant

##### System Information
* LXimage-qt version: 2.0.1
* Distribution & Version: Void  Linux, kernel 6.6.32
* Qt Version: 6.6.0
* liblxqt Version: not installed

**Comment by tsujan** [comment]
Yes, it's misspelled. Thanks for reporting!
